name: tadrib_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  speech_to_text: ^7.0.0                # ✅ أعلى من 6.5.1
  permission_handler: ^12.0.0+1         # ✅ أعلى من 11.1.0
  image_picker: ^1.1.0                  # ✅ أعلى من 1.0.4
  file_picker: ^6.1.1                   # ✅ تمت إضافتها
  go_router: ^15.2.3
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.2.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_secure_storage: ^8.1.0
  url_launcher: ^6.3.0
  dio: ^5.8.0+1
  google_generative_ai: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
