name: tadrib_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.0
  file_picker: ^10.2.0 # <--- تم تحديث هذا السطر إلى الإصدار 7.0.0
  go_router: ^16.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.2.5
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_secure_storage: ^8.1.0
  url_launcher: ^6.3.0
  dio: ^5.8.0+1
  google_generative_ai: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/